### PR TITLE
Todonotes example

### PR DESCRIPTION
**Pull request by floe**
Additional thought (somewhat unrelated): now that there's a draft option, wouldn't it make sense to control other stuff (copyright notice etc.) through that, too?

### CODE REVIEW

**Comment by ayman** [comment]
That would be neat. However were trying to finalize the build for chi 2016.
If you can make an edit quickly and I can test it then that might get in.
No promises because we are going to freeze for build soon.

**Comment by floe** [comment]
OK, I'll see what I can come up with. CHI 2017 otherwise ;-)

**Comment by floe** [comment]
Just caught an unintended side effect: global options are inherited by all packages, and if the option is called `draft`, then e.g. `graphicx` will replace all images with placeholder boxes. So I've renamed it to `chi_draft` in the class and example.

**Comment by ayman** [comment]
Ok - lets not do the copyright bit just yet as that seems more disruptive at the moment.

**Pull request merged**
