### PR TITLE
LibreOffice templates

### PR DESCRIPTION
**Pull request by ghost**
LibreOffice Template

### CODE REVIEW

**Comment by floe** [comment]
Just had a brief look in LO 5.1.6, looks excellent! +1 for merging.

**Comment by honnet** [comment]
Hi @floe!
Are you planning to merge the pull request by @mat-witts ?
It seems very interesting!

**Comment by floe** [comment]
I can't, I'm not a maintainer. @ayman?

**Comment by ayman** [comment]
@floe no longer me...you'll have to ask @sigchi-ops who seems to not reply.

**Comment by ayman** [comment]
These templates were deprecated a while back, closing out pending requests. Please see the newer TAPS information.

**Pull request closed without merging**
