### PR TITLE
add a simple makefile to build the templates

### PR DESCRIPTION
**Pull request by floe**
I usually add a makefile to my paper templates, would be nice to have one there right from the start.

### CODE REVIEW

**Comment by ayman** [comment]
Thanks for this - it's a good generic make file for LaTeX but I'm not sure about adding this to the distribution.  Various folk use different tools (TeXshop, AucTeX, etc.) and putting a makefile presumes there's a single suggested manner.

**Comment by floe** [comment]
Move it to `Extras/`, then?

**Comment by ayman** [comment]
@floe if you address the issues above, we'll take the pull request as an (the) example on how to submit an Extras.

**Comment by floe** [comment]
1) done via 97f19cf
2) done via 75627ba
3) done via 855cd6f
4/5 was already part of PR (44283a3, 65b1af7)

**Pull request merged**
